.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bwscoin_qt test_bwscoin_qt
clean: FORCE
	$(MAKE) -C .. bwscoin_qt_clean test_bwscoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_bwscoin_qt_check
bwscoin-qt bwscoin-qt.exe: FORCE
	 $(MAKE) -C .. bwscoin_qt
